stages:

  - name: sampling
    dependencies: [init]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        data_file: {step: init, output: data_file}
        input_file: {step: init, output: input_file}
        mlflow_args: {step: init, output: mlflow_args_s}
        mlflow_server: {step: init, output: mlflow_server}
        mlflow_username: {step: init, output: mlflow_username}
        output_dir: '{workdir}'
      step: {$ref: 'steps.yml#/sampling'}

  - name: training
    dependencies: [sampling]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        input_file: {step: init, output: input_file}
        mlflow_args: {step: init, output: mlflow_args_t}
        mlflow_server: {step: init, output: mlflow_server}
        mlflow_username: {step: init, output: mlflow_username}
        train_folder: {step: sampling, output: sampling_file}
        output_dir: '{workdir}'
      scatter:
        method: zip
        parameters: [train_folder]
      step: {$ref: 'steps.yml#/training'}

  - name: evaluating
    dependencies: [training]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        data_file: {step: init, output: data_file}
        input_file: {step: init, output: input_file}
        mlflow_args: {step: init, output: mlflow_args_e}
        mlflow_server: {step: init, output: mlflow_server}
        mlflow_username: {step: init, output: mlflow_username}
        model_file: {stages: training, output: output_file, unwrap: true}
        output_dir: '{workdir}'
      scatter:
        method: zip
        parameters: [model_file]
      step: {$ref: 'steps.yml#/evaluating'}

  - name: plotting
    dependencies: [evaluating]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {step: init, output: input_file}
        result_files: {stages: evaluating, output: output_files, flatten: true}
        output_dir: '{workdir}'
        output_name: 'output.txt'
      step: {$ref: 'steps.yml#/plotting'}
