name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  check:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2
    - name: "Install shell script utilities"
      run: |
        sudo apt-get --yes install shellcheck
    - name: "Check shell scripts format"
      run: |
        shellcheck --shell=sh $(find "scripts" -type f -name "*.sh")

  validate:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2
    - name: "Set up Python 3.8"
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: "Install Python dependencies"
      run: |
        pip install packtivity
    - name: "Check workflow steps syntax"
      run: |
        packtivity-validate "workflow/yadage/steps.yml#sampling"
        packtivity-validate "workflow/yadage/steps.yml#training"
        packtivity-validate "workflow/yadage/steps.yml#evaluating"
        packtivity-validate "workflow/yadage/steps.yml#plotting"
